{% set name = "dragon-ml-toolbox" %}
{% set version = "1.2.0" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dragon_ml_toolbox-{{ version }}.tar.gz
  sha256: 29978cc6d8e36ec07578f82351dc12d63dac461d80be637afbe3bcf8f9f58518

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - pandas
    - matplotlib-base
    - scikit-learn

test:
  imports:
    - ml_tools
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/DrAg0n-BoRn/ML_tools
  summary: A collection of tools for data science and machine learning projects
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - DrAg0n-BoRn
